### ISSUE TITLE
Have you considered upgrading to the Teensy 4.0?

### ISSUE THREAD

**Issue by chutsu** [icboredman/TeensyCam-HW#1]
Hi, 

Really like your project and thanks for sharing. I noticed you had some trouble with regards to the High-Speed USB device mode. The Teensy 4.0 seems to be quite an improvement over the 3.6. Namely:

- ARM Cortex-M7 at 600 MHz
- 2 USB ports, both 480 MBit/sec

Or were you having more of a software issue where the Arduino drivers Teensy provided does not support High-Speed USB?

Source: https://www.pjrc.com/store/teensy40.html

**Comment by icboredman** [comment]
Thanks for your interest!
Yes, the problem with Arduino for Teensy 3.6 (teensyduino) was the lack of high-speed USB support. That's why I switched to MCUXpresso.
Teensy 4.0 looks very nice! If only it was around a year ago when I started this development!
Although, bit-banging two MT9V034 sensors at the same time requires a lot of pins and 4.0 seems to have fewer GPIOs than 3.6. Still, I'm going to take a closer look on it.
Thanks.

**Comment by chutsu** [comment]
If you could point me to the right direction / show me some notes in bit-banging the MT9V034 that would be awesome. I'm considering doing a very similar stereo rig to yours so we could potentialy compare notes.

Btw if you need stereo calibration I have coded that up in my [`proto`](https://github.com/chutsu/proto) project. See launch file [here](https://github.com/chutsu/proto/blob/master/proto_ros/launch/calib_stereo.launch) and configuration file [here](https://github.com/chutsu/proto/blob/master/proto_ros/config/calib_intel_d435i.yaml).

Compared to other tool boxes:
- The installation of my code base is trivial, I've written scripts to automate that and I have a [CI to prove it](https://github.com/chutsu/proto/actions).
- Simiar to [Kalibr](https://github.com/ethz-asl/kalibr) I use an AprilGrid, but without the installation headaches of Kalibr.
- Super fast see [example video ](https://www.youtube.com/watch?v=mvisjwUpngg), granted the video does not show the pre-processing step, but as you can see the actual optimization is rather short (this is around 1400 pictures x 2 cams, OpenCV takes around 5-10 minutes on 100 pictures alone).

**Comment by icboredman** [comment]
Basically, for each MT9 module, one would need a I2C interface, 10 pins of data IO and 8 control IO pins.
Take a look at [TeensyCam.c](https://github.com/icboredman/TeensyCam-SW/blob/master/sources/TeensyCam.c), specifically at functions [TakeSnapshot](https://github.com/icboredman/TeensyCam-SW/blob/a7d9e8f0e8e7e943189e58bfd0f1a95039f90173/sources/TeensyCam.c#L201) and [ReadCameraLine](https://github.com/icboredman/TeensyCam-SW/blob/a7d9e8f0e8e7e943189e58bfd0f1a95039f90173/sources/TeensyCam.c#L284).

So far, I have used [fisheye-stereo-calibration](https://github.com/icboredman/fisheye-stereo-calibration) repository based on OpenCV functions, but I will take a look at your tools. Thanks for the info!
